name: 'Build ImageJ Plugin'
on:
  push:
    branches:
    - 'master'
    paths:
    - 'ijplugin/**/*'
  pull_request:
    paths:
    - 'ijplugin/**/*'
permissions:
  contents: 'read'
env:
  THREADS: 2
jobs:
  build:
    runs-on: 'ubuntu-latest'
    steps:
      - name: 'Checkout branch ${{ github.ref_name }}'
        uses: actions/checkout@v4
      - name: Set up JDK 11 for x64
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'zulu'
          cache: maven
      - name: Build
        run: cd ijplugin && mvn package
