name: 'Build ImageJ Plugin'
on:
  push:
    branches:
    - 'master'
    paths:
    - 'ijplugin/**/*'
  pull_request:
    paths:
    - 'ijplugin/**/*'
permissions:
  contents: 'read'
jobs:
  build:
    runs-on: 'ubuntu-latest'
    steps:
      - name: Checkout branch ${{ github.ref_name }}
        uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'zulu'
          cache: maven
      - name: Build
        run: cd ijplugin && mvn package
      - name: Prepare artifact
        run: mkdir staging && cp ijplugin/target/*.jar staging
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: Package
          path: staging/*.jar
          retention-days: 7
